### ISSUE TITLE
Hp Pieschen fehlerhaft

### ISSUE THREAD

**Issue by jonasrichardrichter** [lucasvog/dvbfast#1]
Die Anzeige der Abfahrten am Hp Pieschen ist fehlerhaft.

dvbfast:
![image](https://user-images.githubusercontent.com/33372485/97869165-3f627a00-1d11-11eb-92f0-b667a5387530.png)

dvb.de:
![image](https://user-images.githubusercontent.com/33372485/97869190-4d17ff80-1d11-11eb-8825-936d215dd246.png)

**Comment by lucasvog** [comment]
Danke für das Feedback, der Bug sollte nun gefixt sein. Das Einbinden der Bilder hat sehr geholfen!
